apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-me-deployment
  labels:
    app: web-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-me
  template:
    metadata:
      labels:
        app: web-me
    spec:
      containers:
      - name: web-me
        image: docker.io/adipurnomo/adipurnomo-web:v3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-me
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: myweb
---
apiVersion: v1
kind: Namespace
metadata:
  name: adipurnomo
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-me-ingress
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: web-me
          servicePort: 80
